version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000"  # App 1 exposed on port 3001
    env_file:
      - .env
    restart: unless-stopped

